USE sakila;
-- Challenge - Joining on multiple tables
-- Write SQL queries to perform the following tasks using the Sakila database:

-- 1. List the number of films per category.
SELECT name AS category_name, COUNT(film_id) AS nr_films FROM film INNER JOIN film_category USING (film_id) 
INNER JOIN category USING (category_id) GROUP BY category_name;

-- 2. Retrieve the store ID, city, and country for each store.
SELECT country, city, store_id FROM country
INNER JOIN city USING (country_id) INNER JOIN address USING (city_id)
INNER JOIN store USING (address_id) GROUP BY store_id;

-- 3.  Calculate the total revenue generated by each store in dollars.
SELECT store_id, SUM(amount) AS total_revenue FROM store
INNER JOIN staff USING (store_id) INNER JOIN rental USING (staff_id)
INNER JOIN payment USING (rental_id) GROUP BY store_id;

-- 4.  Determine the average running time of films for each category.
SELECT name AS category_name, ROUND(AVG(length), 2) AS avg_runtime FROM film INNER JOIN film_category USING (film_id) 
INNER JOIN category USING (category_id) GROUP BY category_name;

-- Bonus:
-- 5.  Identify the film categories with the longest average running time.
SELECT name AS category_name, ROUND(AVG(length), 2) AS avg_runtime FROM film INNER JOIN film_category USING (film_id) 
INNER JOIN category USING (category_id) GROUP BY category_name ORDER BY avg_runtime DESC;

-- 6.  Display the top 10 most frequently rented movies in descending order.
SELECT title, COUNT(rental_id) AS nr_rentals FROM film
INNER JOIN inventory USING (film_id) INNER JOIN rental USING (inventory_id)
GROUP BY title ORDER BY nr_rentals DESC LIMIT 10;

-- 7. Determine if "Academy Dinosaur" can be rented from Store 1.
SELECT title, store_id FROM film 
INNER JOIN inventory USING (film_id) INNER JOIN store USING (store_id)
WHERE film_id=(SELECT film_id FROM film WHERE title="ACADEMY DINOSAUR");

-- 8. Provide a list of all distinct film titles, along with their availability status in the inventory. 
-- Include a column indicating whether each title is 'Available' or 'NOT available.'
-- Note that there are 42 titles that are not in the inventory, 
-- and this information can be obtained using a `CASE` statement combined with `IFNULL`."